### ISSUE TITLE
Multi-state Unit Tests Fail

### ISSUE THREAD

**Issue by abalijepalli** [usnistgov/mosaic#54]
Unit tests for MSA fail after most recent pull request (#53). 

Steps to reproduce:

Running the unit tests with

```python
python setup.py mosaic_tests
```

results in 

```javascript
running mosaic_tests
test_e10cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e1cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e2cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e3cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e4cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e5cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e6cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e7cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e8cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e9cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e1seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e1segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e2seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e2segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e3seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e3segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e4seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e4segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e5seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e5segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e10msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e1msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e2msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e3msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e4msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e5msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e6msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e7msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e8msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e9msa (mosaic.utest.mosaicTests.MSATestSuite) ... FAIL
test_e10sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e11sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e12sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e13sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e14sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e15sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e1sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e2sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e3sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e4sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e5sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e6sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e7sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e8sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e9sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e10sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e11sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e12sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e13sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e14sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e15sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e1sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e2sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e3sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e4sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e5sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e6sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e7sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e8sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e9sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok

======================================================================
FAIL: test_e10msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 212, in test_e10msa
    self.runTestCase('testdata/eventLong_11_raw.bin', 'testdata/eventLong_11_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e1msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 185, in test_e1msa
    self.runTestCase('testdata/eventLong_0_raw.bin', 'testdata/eventLong_0_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e2msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 188, in test_e2msa
    self.runTestCase('testdata/eventLong_2_raw.bin', 'testdata/eventLong_2_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e3msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 191, in test_e3msa
    self.runTestCase('testdata/eventLong_3_raw.bin', 'testdata/eventLong_3_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e4msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 194, in test_e4msa
    self.runTestCase('testdata/eventLong_4_raw.bin', 'testdata/eventLong_4_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e5msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 197, in test_e5msa
    self.runTestCase('testdata/eventLong_5_raw.bin', 'testdata/eventLong_5_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e6msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 200, in test_e6msa
    self.runTestCase('testdata/eventLong_6_raw.bin', 'testdata/eventLong_6_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e7msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 203, in test_e7msa
    self.runTestCase('testdata/eventLong_7_raw.bin', 'testdata/eventLong_7_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e8msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 206, in test_e8msa
    self.runTestCase('testdata/eventLong_8_raw.bin', 'testdata/eventLong_8_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

======================================================================
FAIL: test_e9msa (mosaic.utest.mosaicTests.MSATestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 209, in test_e9msa
    self.runTestCase('testdata/eventLong_10_raw.bin', 'testdata/eventLong_10_params.json', msa.multiStateAnalysis)
  File "{path to mosaic}/mosaic/mosaic/utest/mosaicTests.py", line 106, in runTestCase
    self.assertEqual( testobj.mdProcessingStatus, 'normal' )
AssertionError: 'eInvalidEvent' != 'normal'

----------------------------------------------------------------------
Ran 60 tests in 13.643s

FAILED (failures=10)
```

**Comment by forstater** [comment]
Thanks. Let me look into this.

**Comment by forstater** [comment]
*Resolved* Problem was a type mismatch, self.mdRCConst is a list, numpy.all() cannot operate on list directly.

*All tests pass*

Tested by typing:

``python setup.py mosaic_tests
``

Output

```python 
running mosaic_tests
test_e10cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e1cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e2cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e3cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e4cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e5cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e6cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e7cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e8cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e9cla (mosaic.utest.mosaicTests.CLATestSuite) ... ok
test_e1seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e1segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e2seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e2segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e3seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e3segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e4seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e4segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e5seg (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e5segP (mosaic.utest.mosaicTests.EventPartitionTestSuite) ... ok
test_e10msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e1msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e2msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e3msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e4msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e5msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e6msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e7msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e8msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e9msa (mosaic.utest.mosaicTests.MSATestSuite) ... ok
test_e10sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e11sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e12sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e13sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e14sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e15sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e1sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e2sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e3sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e4sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e5sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e6sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e7sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e8sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e9sra (mosaic.utest.mosaicTests.SRATestSuite) ... ok
test_e10sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e11sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e12sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e13sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e14sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e15sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e1sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e2sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e3sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e4sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e5sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e6sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e7sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e8sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok
test_e9sse (mosaic.utest.mosaicTests.SSETestSuite) ... ok

----------------------------------------------------------------------
Ran 60 tests in 32.272s
```
