### ISSUE TITLE
Mosaic crashes if data file is shorter than requested data block size

### ISSUE THREAD

**Issue by shadowk29** [usnistgov/mosaic#65]
If the total length of the file is less than the blockSizSece parameter in eventSegment settings, mosaic crashes (error follows). How does mosaic handle the end of files if they don't fit into an integer multiple of blocksize currently?
```
Traceback (most recent call last):
  File "C:\Users\xxxxxxx\Documents\python\file conversion\analysis.py", line 31, in <module>
    msa.multiStateAnalysis
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\SingleChannelAnalysis.py", line 80, in Run
    run_eventpartition( self.trajDataObj, self.eventPartitionHnd, self.eventProcHnd, self.settingsDict )
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\SingleChannelAnalysis.py", line 28, in run_eventpartition
    EventPartition.PartitionEvents()
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaEventPartition.py", line 163, in PartitionEvents
    self._setuppartition()
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaEventPartition.py", line 340, in _setuppartition
    [ self.meanOpenCurr, self.sdOpenCurr, self.slopeOpenCurr ] = self._openchanstats(self.trajDataObj.previewdata(self.nPoints))
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaTrajIO.py", line 312, in previewdata
    return self.previewdata(n)
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaTrajIO.py", line 312, in previewdata
    return self.previewdata(n)

  [...repeated several hundred times...]

  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaTrajIO.py", line 312, in previewdata
    return self.previewdata(n)
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaTrajIO.py", line 312, in previewdata
    return self.previewdata(n)
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaTrajIO.py", line 311, in previewdata
    self._appenddata()
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaTrajIO.py", line 362, in _appenddata
    fname=self.popfnames()
  File "C:\Users\xxxxxxx\My Documents\Analysis\mosaic\mosaic\metaTrajIO.py", line 459, in popfnames
    raise EmptyDataPipeError("End of data.")
EmptyDataPipeError: End of data.
```

**Comment by abalijepalli** [comment]
It appears to be failing as expected. MOSAIC reads data in blocks set by the `BlockSize` parameter. When it is not able to fill a block, it returns an ```EmptyDataPipeError```. If you had a long data set, the last data block may not be filled and is therefore not analyzed. For example with 12.1 s of data and `BlockSize` of 1.0 s, the last 0.1 s are not analyzed. If the length of the data set is shorter than the `BlockSize`, the analysis won't run.

**Comment by abalijepalli** [comment]
Actually, the problem was in the `previewdata` function in `metaTrajIO`. Pushing the fix now.
