### ISSUE TITLE
Test Suite Error - fileview

### ISSUE THREAD

**Issue by forstater** [usnistgov/mosaic#77]
**Commit**: bdf37308fce84d3524351123e367718beb3d56e1
**Problem:** Mosaic test-suite unable to find mosaicgui.fileview.fileview 
**Step(s) to replicate** `python setup.py mosaic_tests`
**Notes** I've replicated this problem on both brewed python and anaconda python environments. 
**Error details** 
```

======================================================================
ERROR: mosaic.utest.mosaicTests.ModuleImport_TestSuite.test_moduleImport('mosaicgui.fileview.fileview',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jhf1/anaconda/envs/testGround/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jhf1/Projects/mosaic/mosaic/utest/mosaicTests.py", line 139, in runTestCase
    module=__import__(modulename)
ImportError: No module named fileview.fileview
```

**Comment by abalijepalli** [comment]
Fixed in 53a21cb386033f4898012b2ae428179a930364ec
