### ISSUE TITLE
runMOSAIC script crash

### ISSUE THREAD

**Issue by shadowk29** [usnistgov/mosaic#81]
When running python runMOSAIC on Windows I get the following:

Traceback (most recent call last):
  File "runMOSAIC", line 30, in <module>
    main()
  File "runMOSAIC", line 12, in main
    update_rcParams()
  File "C:\Users\kbrig035\My Documents\Analysis\mosaic\mosaicgui\mplwidget.py", line 26, in update_rcParams
    'axes.prop_cycle' : matplotlib.cycler(color=['#3B3D91', '#DB5E00', 'k']),
AttributeError: 'module' object has no attribute 'cycler'

**Comment by shadowk29** [comment]
fixed by updating to matplotlib 1.5.1
