### ISSUE TITLE
Analysis with Chimera data fails when output logs are present

### ISSUE THREAD

**Issue by abalijepalli** [usnistgov/mosaic#84]
Loading a previous analysis or starting a new analysis in a folder containing Chimera files with a '.log' extension fails when there are  previous output log (e.g., eventProcessing-<date-time>.log') files present in the folder. Under this condition, an exception is raised.

>Traceback (most recent call last):
  File "<mosaic_root>/mosaic/mosaicgui/settingsview.py", line 388, in OnSelectPath
    self.OnDataPathChange()
  File "<mosaic_root>/mosaic/mosaicgui/settingsview.py", line 399, in OnDataPathChange
    self.trajViewerWindow.refreshPlot()
  File "<mosaic_root>/mosaic/mosaicgui/trajview/trajview.py", line 153, in refreshPlot
    self.nPoints=int(self.blockSize*self.IOObject.FsHz)
  File "<mosaic_root>/mosaic/mosaic/trajio/metaTrajIO.py", line 195, in FsHz
    self._initPipe()
  File "<mosaic_root>/mosaic/mosaic/trajio/metaTrajIO.py", line 494, in _initPipe
    self._appenddata()
  File "<mosaic_root>/mosaic/mosaic/trajio/metaTrajIO.py", line 390, in _appenddata
    self.rawData=self.readdata( fname )
  File "<mosaic_root>/mosaic/mosaic/trajio/chimeraTrajIO.py", line 166, in readdata
    return self.readBinaryFile(fname)
  File "<mosaic_root>/mosaic/mosaic/trajio/chimeraTrajIO.py", line 187, in readBinaryFile
    return np.memmap(fname, dtype=self.ColumnTypes, mode='r', offset=self.HeaderOffset)[self.IonicCurrentColumn]
  File "~/.virtualenvs/mosaicENV/lib/python2.7/site-packages/numpy/core/memmap.py", line 232, in __new__
    raise ValueError("Size of available data is not a "
ValueError: Size of available data is not a multiple of the data-type size.

**Comment by shadowk29** [comment]
If eventProcessing.log is the only other .log file that would be present, we could simply remove it from the list that glob returns. Not a particularly elegant solution, though.
