### ISSUE TITLE
Mosaic executable fails to load on OSX 10.12.1

### ISSUE THREAD

**Issue by forstater** [usnistgov/mosaic#90]
**Issue:**  Executable Mosaic.app fails on OSX 10.12.1.
** Mosaic Version:** 1.3 (f0e754c6b66c46c4463ffde179b6207a516f7dd7)
** Operating System:** OSX 10.12.1

**Submitted by external user:**

> Do you have any experience running Mosaic on MacOSX 10.12.1?   I downloaded the app off of your web site and when I double click on the app, it shows up momentarily in the dock, then disappears.

>I’ve searched the web to look into issues with other apps when using MacOS Sierra and have followed their advice.   For example, removing the plist file, reset PRAM, etc. with no luck.  I ran Techtool and Disk Utility to see if there were any abnormalities in the file structure/directory on my hard drive - nothing popped up.  Do you have any advice?

**Comment by forstater** [comment]
_User was instructed to run mosaic application within terminal and provide output for debugging:_

- In Finder, ctrl-click the MOSAIC application and click “_Show Package Contents”_
- Open a terminal window `/Applications/Utilities/Terminal.app`
- Drag the file `Contents/MacOS/MOSAIC` to the Terminal window and hit _Return_.



**Output is as follows:**

``` 

macbook:~ username$ /Applications/MOSAIC.app/Contents/MacOS/MOSAIC 
/Applications/MOSAIC.app/Contents/MacOS/matplotlib/font_manager.py:273: UserWarning:
Matplotlib is building the font cache using fc-list. This may take a moment.

Traceback (most recent call last):
   File "runMOSAIC", line 32, in <module>
   File "runMOSAIC", line 19, in startMOSAIC
   File "mosaicgui/updateService.py", line 61, in CheckUpdate
   File "mosaicgui/updateService.py", line 146, in _getUpdateInfo
NameError: global name 'logger' is not defined
Failed to execute script runMOSAIC```
